[package]
name = "nix-secrets"
version = "0.1.0"
edition = "2024"

[dependencies]
age = { version = "0.12.1", default-features = false, features = ["cli-common", "ssh", "armor", "plugin"] }
chrono = { version = "0.4.45", default-features = false, features = ["clock"] }
clap = { version = "4.6.4", features = ["derive", "env"] }
eyre = { version = "0.6.12" }
nix = { version = "0.31.3", features = ["user", "hostname", "fs"] }
scopeguard = "1.2.0"
serde = { version = "1.0.229", features = [ "derive" ] }
serde_json = "1.0.151"
sha2 = "0.10.0"
shlex = { version = "2.0.1", default-features = false }
sys-mount = "3.1.0"
thiserror = "2.0.19"
tracing = { version = "0.1.44", features = ["max_level_trace", "release_max_level_info"] }
tracing-subscriber = { version = "0.3.23", features = ["env-filter"] }

[profile.dev]
opt-level = 0
debug = 0
panic = "unwind"

[profile.release]
opt-level = "z"
strip = true
lto = true
codegen-units = 1
panic = "abort"

[lints.clippy]
nursery = { level = "deny", priority = -1 }
pedantic = { level = "deny", priority = -1 }

unwrap_used = "deny"
expect_used = "deny"
indexing_slicing = "deny"
arithmetic_side_effects = "deny"
unreachable = "deny"
unimplemented = "deny"
unchecked_time_subtraction = "deny"
todo = "deny"
string_slice = "deny"
panic_in_result_fn = "deny"
panic = "deny"
exit = "deny"
as_conversions = "deny"
