[package]
name = "nix-secrets"
version = "0.1.0"
edition = "2024"

[dependencies]
age = { version = "0.12.1", default-features = false, features = ["cli-common", "ssh", "armor", "plugin"] }
chrono = { version = "0.4.45", default-features = false, features = ["clock"] }
clap = { version = "4.6.4", features = ["derive", "env"] }
eyre = { version = "0.6.12", default-features = false }
nix = { version = "0.31.3", features = ["user", "hostname", "fs"] }
scopeguard = "1.2.0"
serde = { version = "1.0.229", features = [ "derive" ] }
serde_json = "1.0.151"
shlex = { version = "2.0.1", default-features = false }
simple-eyre = "0.3.1"
sys-mount = "3.1.0"
tracing = { version = "0.1.44", features = ["max_level_trace", "release_max_level_info"] }
tracing-subscriber = { version = "0.3.23", features = ["env-filter"] }

[profile.dev]
opt-level = 0
debug = 0
panic = "unwind"

[profile.release]
opt-level = "z"
strip = true
lto = true
codegen-units = 1
panic = "abort"

[lints.clippy]
nursery = { level = "warn", priority = -1 }
pedantic = { level = "warn", priority = -1 }

blanket_clippy_restriction_lints = "allow"
restriction = { level = "warn", priority = -1 }

arbitrary-source-item-ordering = "allow"
arithmetic_side_effects = "allow"
exhaustive-enums = "allow"
exhaustive-structs = "allow"
implicit_return = "allow"
indexing_slicing = "allow"
integer_division_remainder_used = "allow"
min_ident_chars = "allow"
missing_docs_in_private_items = "allow"
mod_module_files = "allow"
pattern_type_mismatch = "allow"
print_stderr = "allow"
question_mark_used = "allow"
semicolon_inside_block = "allow"
separated_literal_suffix = "allow"
similar_names = "allow"
single_call_fn = "allow"
std_instead_of_alloc = "allow"
std_instead_of_core = "allow"
pub_use = "allow"
pub_with_shorthand = "allow"
# Generally not useful
cognitive_complexity = "allow"
too_many_lines = "allow"

doc_paragraphs_missing_punctuation = "allow"
