[book]
title = "nix-secrets"
authors = ["nix-secrets maintainers"]
description = "A postmodern secrets manager for NixOS."
language = "en"

[build]
create-missing = false

[output.html]
git-repository-url = "https://github.com/unnamed-systems/nix-secrets"
edit-url-template = "https://github.com/unnamed-systems/nix-secrets/edit/master/docs/{path}"
additional-css = ["theme/pagetoc.css", "theme/tabs.css"]
additional-js  = ["theme/pagetoc.js", "theme/tabs.js", "theme/no-edit-generated.js"]
no-section-label = true
sidebar-header-nav = false

[output.html.print]
enable = false

[preprocessor.treesitter]
command = "mdbook-treesitter"
languages = ["nix"]

[preprocessor.pagetoc]
scroll_offset = 10

[preprocessor.tabs]